apiVersion: v1
kind: Service
metadata:
  labels:
    name: recommendationservice
  name: recommendationservice
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
  selector:
    app: recommendationservice
  type: ClusterIP
