name: Run tests for OTUS homework

on:
  push:
    branches: kubernetes-*
  pull_request:
    branches: kubernetes-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: "https://github.com/express42/otus-platform-tests.git"
        ref: github-actions

    - name: Run tests
      run: curl https://raw.githubusercontent.com/express42/otus-platform-tests/github-actions/run.sh | bash
