name: Run tests for OTUS homework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: curl https://raw.githubusercontent.com/express42/otus-platform-tests/2020-04/run.sh | bash
