name: Run tests for OTUS homework

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches-ignore: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: curl https://raw.githubusercontent.com/express42/otus-platform-tests/github-actions/run.sh | bash
